python run_summarization.py \
    --model_name_or_path t5-base \
    --dataset_name cnn_dailymail \
    --dataset_config "2.0.0" \
    --source_prefix "summarize: " \
    --preprocessing_num_workers 16 \
    --max_source_length 512 \
    --max_target_length 128 \
    --logging_strategy steps \
    --logging_steps 50 \
    --evaluation_strategy steps \
    --eval_steps 5000 \
    --save_strategy steps \
    --save_steps 5000 \
    --save_total_limit 4 \
    --metric_for_best_model "rouge2" \
    --output_dir ./tst-summarization \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --do_predict \
    --max_steps 262144 \
    --per_device_train_batch_size=16 \
    --per_device_eval_batch_size=4 \
    --warmup_steps 10000 \
    --predict_with_generate \
    --num_beams 4 \
    --learning_rate 0.00001 \
    --seed 42 \
